# Generated by Django 4.1.6 on 2023-02-04 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 2, 4, 7, 11, 46, 916628, tzinfo=datetime.timezone.utc)),
        ),
    ]
