# Generated by Django 4.1.6 on 2023-02-04 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_id_post_author_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 8, 4, 30, 113694, tzinfo=datetime.timezone.utc)),
        ),
    ]
